#!/bin/sh
# @(#) balden@seth2.belcarratech.com|otg/functions/isotest/iso_fermat|20051116204957|20615
# 
#      Copyright 2005-2006 Motorola, Inc.
#
# Changelog:
# Date               Author           Comment
# -----------------------------------------------------------------------------
# 12/12/2005         Motorola         dn Initial distribution
# 10/18/2006         Motorola         ma sk pw Add Open Src Software language
#
# This Program is distributed in the hope that it will
# be useful, but WITHOUT ANY WARRANTY;
# without even the implied warranty of
# MERCHANTIBILITY or FITNESS FOR A
# PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.

# This program is free software; you can redistribute it
# and/or modify it under the terms of the GNU General
# Public License as published by the Free Software
# Foundation; either version 2 of the License, or (at
# your option) any later version.  You should have
# received a copy of the GNU General Public License
# along with this program; if not, write to the Free
# Software Foundation, Inc., 675 Mass Ave,
# Cambridge, MA 02139, USA

XFER=$1
PATTERN=$2
if [ -z "$PATTERN" ]
then
	PATTERN="0x1,0x8,1,2,3,4,5,6,7,8"
fi
echo "Using PATTERN='$PATTERN'"
set -x

insmod  /tmp/usbdcore.o 
insmod /tmp/usbdprocfs.o

insmod  /tmp/isotest_fd.o vendor_id=0xfff0 product_id=0xfff1 in=$XFER out=$XFER xmit_pattern="$PATTERN" print_all=0 fermat=1 custom=0

insmod  /tmp/au1x00_bi.o 
echo "enable" > /proc/usbd-switch


set +x
echo -n "INSERT CABLE"
sleep 15
echo -n ";  REMOVE CABLE AND PRESS RETURN"
read junk
set -x
cp /proc/isotest_fd client
cp /proc/isotest_host host
echo "disable" > /proc/usbd-switch

rmmod au1x00_bi
rmmod isotest_fd
rmmod usbdprocfs
rmmod usbdcore

