# Function Drivers
#include /vobs/linuxjava/drivers_1/usb_driver/.config

obj-y += generic/
obj-y += acm/
#obj-y += msc/
#obj-y += mouse/
obj-y += network/
# obj-y += isotest/
obj-y += mtp/
obj-y += android_adb/


