#extra-y := mc13783.o mxc-hrt.o mxc-ocd.o mxc-pcd.o mxc-procfs.o mxc-l26.o mxc-hcd.o
#obj-y := empty.o

obj-$(CONFIG_OTG_ZASEVB) += hcd_test.o
hcd_test-objs                                           := hcd-test.o
